name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: json-to-file
  # You may pin to the exact commit or the version.
  # uses: devops-actions/json-to-file@709b07a59822663e2ead98d5d62139bfb80ab50e
  uses: devops-actions/json-to-file@v1.0.5
  with:
    # The json you want to store
    json: 
    # The filename you want to store the json in
    filename: 
          
    - name: Build
      run: 
        npm install
        npx webpack
